-- criando database-- 
CREATE DATABASE DB_SERVICO_RH; 
-- usando --
USE DB_SERVICO_RH;

-- criando tabela com atributos-- 
CREATE TABLE TB_FUNCIONARIOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(1000),
IDADE INT,
FUNCAO CHAR(255),
PRIMARY KEY (ID)
);
-- inserindo valores nos dados --
INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, FUNCAO) 
VALUES("Flavia", 19, "Deva FullStack");

-- CONSULTANDO A TEBELA --
SELECT * FROM db_servico_rh.tb_funcionarios;
-- ADICIONANDO MAIS COLUNAS --
ALTER TABLE TB_FUNCIONARIOS ADD (ENDERECO VARCHAR(100), EMAIL CHAR(50));
-- DELETANDO COLUNA --
ALTER TABLE TB_FUNCIONARIOS DROP column ENDERECO;
-- ADICIONANDO A COLUNA DE SALARIO --
ALTER TABLE TB_FUNCIONARIOS ADD (SALARIO NUMERIC (9,2));
-- INSERINDO DADOS --
INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, FUNCAO, EMAIL, SALARIO)
VALUES("Alex", 19, "Estudante","alex@gmail.com",1600.00);
INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, FUNCAO, EMAIL, SALARIO)
VALUES("Maria", 22, "Medica","maria@gmail.com",8000.00);
-- INSERINDO DADOS FALTANTES --
UPDATE TB_FUNCIONARIOS SET SALARIO = 1984.99 WHERE ID = 1;
UPDATE TB_FUNCIONARIOS SET EMAIL = "jihye83@hotmail.com" WHERE ID = 1; 
-- MAIOR E MENOR SALARIO --
SELECT * FROM TB_FUNCIONARIOS WHERE SALARIO > 2000.00; 
SELECT NOME, SALARIO FROM TB_FUNCIONARIOS WHERE SALARIO > 2000.00;
SELECT * FROM TB_FUNCIONARIOS WHERE SALARIO < 2000.00;
SELECT NOME, SALARIO FROM TB_FUNCIONARIOS WHERE SALARIO < 2000.00;
-- ATUALIZANDO UM REGISTRO --
UPDATE TB_FUNCIONARIOS SET NOME = "Flávia Santana" WHERE ID = 3;
