CREATE DATABASE DB_FARMACIA_BEM_ESTAR;
USE DB_FARMACIA_BEM_ESTAR;
-- 1 --
CREATE TABLE TB_CATEGORIAS(
ID INT AUTO_INCREMENT,
CAT VARCHAR(100) NOT NULL,
FORNE VARCHAR (100) NOT NULL, 
PRIMARY KEY (ID)
);
-- 2,3 --
CREATE TABLE TB_PRODUTO(
ID INT AUTO_INCREMENT,
NOME VARCHAR(50) NOT NULL,
PRECO DECIMAL(6,2) NOT NULL,
QTD INT NOT NULL,
DESCRICAO VARCHAR (100) NOT NULL,
CAT_ID INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (CAT_ID) REFERENCES TB_CATEGORIAS(ID)
);
-- 4 --
INSERT INTO TB_CATEGORIAS(CAT, FORNE)
VALUES("REMEDIO", "EUROFARMA"),
("REMEDIO", "EMS"),
("CURATIVOS", "NEEDS"),
("COSMETICOS", "LOREAL"),
("FRALDAS", "PAMPERS");
-- 5 --
INSERT INTO TB_PRODUTO(NOME, PRECO, QTD, DESCRICAO, CAT_ID)
VALUES ("DIOVAN", 130.00, 10, "REMEDIO DE PRESSAO", 1),
("RESFENOL", 30.00, 10, "REMEDIO DE GRIPE", 2),
("SHAMPOO", 85.00, 10, "SHAMPOO HIDRATA", 4),
("BAND AID", 20.00, 10, "CURATIVO", 1),
("SALOMPAS", 8.00, 10, "ADESIVO PARA ALIVIAR DOR", 3),
("LOREAL", 99.00, 10, "COLORACAO PARA CABELO",4),
("PAMPERS", 56.00, 10, "FRALDAS MEDIOS", 5),
("HUGGIES", 64.00, 10, "FRALDAS PEQUENAS", 5);
-- 6 --
SELECT NOME, PRECO FROM TB_PRODUTO WHERE PRECO > 50.00;
-- 7 --
SELECT NOME, PRECO FROM TB_PRODUTO WHERE PRECO > 5.00 AND PRECO < 60.00;
-- 8 --
SELECT NOME, PRECO, DESCRICAO FROM TB_PRODUTO WHERE NOME LIKE "%C%";
-- 9 -- 
SELECT NOME, PRECO, DESCRICAO, CAT_ID FROM TB_PRODUTO INNER JOIN TB_CATEGORIAS ON
TB_PRODUTO.CAT_ID = TB_CATEGORIAS.ID;
-- 10 PEGANDO SOMENTE DADOS DA COLUNA QUE EU QRO--
SELECT NOME, PRECO, DESCRICAO, CAT_ID, CAT FROM TB_PRODUTO INNER JOIN TB_CATEGORIAS ON
TB_PRODUTO.CAT_ID = TB_CATEGORIAS.ID WHERE CAT = "COSMETICOS";

