CREATE DATABASE DB_PIZZARIA_LEGAL;
USE DB_PIZZARIA_LEGAL;
-- 1 --
CREATE TABLE TB_CATEGORIA(
ID BIGINT AUTO_INCREMENT NOT NULL,
CAT VARCHAR (100) NOT NULL,
TAMANHO CHAR (50) NOT NULL,
PRIMARY KEY (ID)
);
-- 2,3 --
CREATE TABLE TB_PIZZA(
ID BIGINT AUTO_INCREMENT NOT NULL,
NOME VARCHAR (100) NOT NULL,
PRECO DECIMAL (5,2) NOT NULL,
QTPIZZA INT (10)NOT NULL,
INGREDIENTE VARCHAR(100) NOT NULL,
CAT_ID BIGINT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (CAT_ID) REFERENCES TB_CATEGORIA(ID)
);
-- 4 --
INSERT INTO TB_CATEGORIA(CAT, TAMANHO)
VALUES("SALGADO","PEQUENO"),
("SALGADO", "MEDIO"),
("SALGADO", "GRANDE"),
("DOCE", "PEQUENO"),
("DOCE", "MEDIO");
-- 5 --
INSERT INTO TB_PIZZA(NOME, PRECO, QTPIZZA, INGREDIENTE, CAT_ID)
VALUES("MARGUERITA", 59.99, 10, "QUEIJO", 1),
("PORTUGUESA", 100.99, 10, "PRESUNTO", 2),
("BRASILEIRA", 40.99, 10, "CEBOLA E QUEIJO", 3),
("NUTELLA", 20.99, 10, "NUTELLA", 4),
("BRIGADEIRO", 50.99, 10, "CHOCOLATE", 5),
("PERUANA", 100.99, 10, "PERU, QUEIJO", 1),
("BAHIANA", 120.99, 10, "CALABRESA, CEBOLA", 2),
("MILHO VERDE", 70.99, 10, "MILHO , BACON", 3);

SELECT * FROM TB_CATEGORIA;
SELECT * FROM TB_PIZZA;
-- 6 --
SELECT * FROM TB_PIZZA WHERE PRECO > 45.00;
-- 7 -- 
SELECT * FROM TB_PIZZA WHERE PRECO > 50.00 AND PRECO < 100.00;
-- 8 --
SELECT * FROM TB_PIZZA WHERE NOME LIKE "%M%";
-- 9 --
SELECT * FROM TB_CATEGORIA INNER JOIN TB_PIZZA ON
TB_CATEGORIA.ID = TB_PIZZA.CAT_ID;
-- 10 --
SELECT * FROM TB_CATEGORIA INNER JOIN TB_PIZZA ON
TB_CATEGORIA.ID = TB_PIZZA.CAT_ID WHERE CAT = "DOCE";

